# CLEANING STEPS OF THE DATA EXTRACTED FROM  WEBSCRAPPING

In [3]:
import pandas as pd

In [4]:
# Reading the exported csv file gotten from the immonet webscrapping
df = pd.read_csv("full_list.csv")

In [5]:
# checking the first 5 rows 
df.head()

                   0
0        470 ; 56.85
1        720 ; 95.13
2       1.870 ; 75.0
3  1.699,28 ; 108.58
4         879 ; 64.0

The DataFrame above contain the price and its corresponding size in meter square(mÂ²) with both seperated with semi-colon , all in one column which was scrapped from the immonet listing websites. 
The goal of this cleaning is to create a clean DataFrame with both price and the size being in their respective column.
Our approach is going to create an empty list that will take in all mapped prices and sizes for easy look.

In [7]:
rough_list = []
for price_size in df["0"]:
    rough_list.append(price_size)
print(rough_list)

['470 ; 56.85', '720 ; 95.13', '1.870 ; 75.0', '1.699,28 ; 108.58', '879 ; 64.0', '1.119,04 ; 69.94', '656 ; 52.5', '3.216,57 ; 185.5', '401,58 ; 57.62', '1.875 ; 126.78', '1.091,70 ; 96.1', '1.100 ; 53.0', '1.890 ; 147.36', '498,50 ; 33.21', '3.181,10 ; 212.1', '735 ; 59.37', '2.141,64 ; 134.02', '1.353 ; 123.0', '1.157,90 ; 99.2', '2.485 ; 99.39', '420,40 ; 42.4', '699 ; 70.28', '2.864,67 ; 144.17', '659,60 ; 65.96', '1.123,20 ; 35.1', '1.300 ; 42.5', '949 ; 88.3', '659 ; 58.07', '1.005,35 ; 101.55', '629 ; 54.8', '415,50 ; 42.0', '1.900 ; 116.0', '2.900 ; 132.0', '850 ; 95.95', '852,93 ; 66.9', '1.700 ; 90.0', '997,50 ; 105.0', '1.020 ; 29.13', '1.335,71 ; 113.1', '1.400 ; 74.0', '2.175 ; 119.85', '437,18 ; 53.26', '1.450 ; 88.0', '1.600 ; 105.0', '1.000 ; 53.7', '599 ; 53.74', '1.535 ; 87.81', '723,94 ; 56.25', '558,11 ; 23.86', '900 ; 62.0', '649 ; 22.35', '670 ; 54.6', '734,75 ; 59.35', '790,65 ; 29.87', '700 ; 41.0', '598 ; 46.02', '1.568 ; 98.0', '430 ; 58.55', '900 ; 91.0', '600 ; 67.0', '1.150 ; 115.0', '1.677 ; 140.0', '994 ; 83.0', '254,34 ; 39.13', '352 ; 57.7', '1.400 ; 72.55', '1.650 ; 103.33', '901,77 ; 66.29', '950 ; 80.0', '726 ; 65.76', '3.475 ; 178.4', '1.136,68 ; 72.4', '1.460,98 ; 74.5', '1.484,18 ; 98.43', '1.412,95 ; 97.445', '712,68 ; 59.39', '799 ; 73.26', '1.150 ; 81.0', '987 ; 93.0', '687,22 ; 60.23', '750 ; 50.0', '699 ; 57.35', '791,22 ; 29.76', '1.875 ; 117.23', '1.350 ; 104.0', '1.125 ; 83.37', '707 ; 74.38', '1.249 ; 43.0', '1.249 ; 31.97', '1.330,44 ; 53.23', '9.500 ; 400.0', '1.542,87 ; 91.57', '1.484,98 ; 86.79', '532,17 ; 89.44', '1.567,43 ; 129.54', '644,10 ; 64.41', '499 ; 37.1', '550 ; 20.5', '2.275 ; 182.0', '606 ; 62.38', '912,49 ; 54.9', '874,46 ; 76.0', '690,91 ; 48.0', '218,41 ; 36.29', '2.815 ; 102.36', '2.440 ; 130.0', '520 ; 58.0', '2.305,02 ; 171.76', '540 ; 20.5', '1.450 ; 1.', '1.496,06 ; 90.67', '1.190 ; 85.27', '449 ; 33.54', '1.559,01 ; 102.23', '1.654,15 ; 95.23', '1.480 ; 102.56', '5.700 ; 186.0', '1.199 ; 93.93', '848,34 ; 60.38', '955 ; 56.0', '1.646,09 ; 94.17', '578,16 ; 72.27', '1.719,32 ; 99.44', '1.158,95 ; 89.15', '1.550 ; 77.79', '1.196,62 ; 157.45', '2.146,38 ; 122.65', '1.149 ; 31.9', '719 ; 73.97', '800 ; 75.0', '1.553,89 ; 88.0', '1.460 ; 64.86', '1.907,17 ; 98.67', '1.250 ; 78.0', '1.270 ; 79.2', '1.419 ; 129.0', '1.210 ; 115.39', '259,94 ; 30.59', '1.650 ; 126.7', '1.941,94 ; 122.83', '903 ; 64.5', '1.270 ; 43.71', '1.663,47 ; 98.43', '1.584 ; 91.84', '950 ; 47.63', '640 ; 54.12', '746,10 ; 49.74', '3.265,42 ; 143.54', '1.800 ; 96.6', '1.901,50 ; 86.42', '1.590 ; 86.55', '1.545 ; 91.86', '584,40 ; 59.03', '949 ; 29.95', '1.019,16 ; 85.0', '990 ; 90.0', '1.840 ; 108.0', '268 ; 15.0', '902,48 ; 66.85', '649 ; 70.68', '790,97 ; 68.78', '1.285 ; 171.06', '936,99 ; 74.07', '1.295,53 ; 69.1', '1.471,63 ; 96.5', '650 ; 49.0', '1.450 ; 131.0', '2.759 ; 141.32', '473,24 ; 60.75', '1.207 ; 46.5', '460 ; 68.54', '856,06 ; 26.79', '699 ; 36.0', '491,88 ; 68.88', '1.992 ; 60.0', '1.150 ; 50.0', '761,25 ; 101.5', '2.150 ; 93.2', '1.950 ; 104.0', '876,79 ; 73.31', '638,55 ; 58.05', '1.289 ; 101.0', '1.800 ; 82.5', '549 ; 41.42', '965 ; 60.98', '613,41 ; 53.34', '781,50 ; 71.04', '1.450,44 ; 85.12', '1.190,95 ; 94.52', '1.072,53 ; 63.09', '888 ; 78.95', '885 ; 59.0', '600 ; 67.88', '1.050 ; 65.0', '1.809,22 ; 95.98', '2.053,50 ; 136.9', '1.185 ; 86.0', '477,33 ; 64.33', '3.800 ; 158.0', '449 ; 35.69', '1.020 ; 42.29', '1.487,50 ; 87.5', '320 ; 43.68', '780 ; 39.0', '1.344,87 ; 99.62', '770 ; 94.21', '850 ; 95.1', '2.600 ; 130.0', '819 ; 86.03', '1.380 ; 110.72', '1.598,67 ; 103.14', '1.295 ; 122.67', '897 ; 44.87', '1.261,50 ; 63.17', '472,83 ; 62.96', '1.310 ; 43.1', '799 ; 71.41', '538 ; 19.34', '1.571,40 ; 87.3', '1.218,92 ; 90.29', '1.190 ; 88.61', '739 ; 78.24', '1.405 ; 79.33', '4.200 ; 163.0', '288,80 ; 44.43', '1.400 ; 86.0', '1.000 ; 74.95', '844,25 ; 91.0', '3.111 ; 160.0', '420 ; 19.0', '1.625 ; 82.83', '515,77 ; 70.75', '459 ; 35.69', '840,15 ; 59.27', '5.100 ; 123.0', '1.299 ; 55.0', '1.520 ; 81.37', '980 ; 69.08', '1.314,12 ; 80.0', '1.195 ; 99.63', '630 ; 63.0', '1.050 ; 43.55', '970,68 ; 54.07', '1.600 ; 94.0', '4.732 ; 182.0', '1.249 ; 31.07', '792,99 ; 29.4', '370 ; 60.15', '442,33 ; 69.19', '1.330,85 ; 73.94', '1.942,50 ; 129.5', '1.067,89 ; 102.88', '364,76 ; 51.96', '631,80 ; 36.12', '1.525 ; 82.27', '1.699,30 ; 108.86', '1.181 ; 63.53', '579 ; 53.98', '1.491,66 ; 82.87', '294,20 ; 29.4', '800 ; 72.0', '719 ; 74.34', '494,22 ; 65.17', '281,50 ; 40.1', '1.200 ; 103.93', '1.018,50 ; 33.95', '1.200 ; 60.0', '380 ; 40.0', '935 ; 55.0', '890 ; 51.0', '979 ; 101.73', '773 ; 70.0', '769 ; 84.77', '557 ; 55.7', '2.299 ; 129.59', '980 ; 90.7', '1.148 ; 85.01', '725 ; 58.0', '518,82 ; 22.9', '1.486,52 ; 104.81', '856,04 ; 26.79', '293 ; 43.7', '500 ; 77.0', '979,53 ; 55.66', '1.249 ; 98.99', '936 ; 80.0', '950 ; 50.0', '499 ; 37.21', '1.450 ; 73.0', '630,23 ; 66.34', '1.200 ; 80.05', '375,38 ; 57.75', '810 ; 66.2', '1.878 ; 197.59', '1.020 ; 68.8', '2.000 ; 92.0', '1.693,85 ; 98.04', '1.350 ; 92.0', '1.200 ; 3016.0', '1.270,58 ; 74.74', '949 ; 90.12', '2.145 ; 143.0', '1.435 ; 77.07', '2.100 ; 105.0', '1.869,90 ; 230.0', '475 ; 72.0', '2.750 ; 110.0', '673,71 ; 63.2', '350 ; 43.28', '633,33 ; 68.1', '1.149 ; 63.0', '1.132,34 ; 62.0', '649 ; 69.7', '1.100 ; 100.0', '2.300 ; 145.0', '1.545 ; 103.15', '550 ; 67.81', '1.635,26 ; 148.66', '673,92 ; 74.88', '440 ; 61.2', '449 ; 37.31', '600 ; 45.5', '2.500 ; 134.0', '1.117,50 ; 37.25', '1.300 ; 96.33', '2.250 ; 127.0', '839,29 ; 80.71', '1.478 ; 77.79', '2.448 ; 150.0', '1.069,81 ; 110.57', '4.360 ; 171.8', '2.019,68 ; 115.41', '491 ; 51.72', '1.023,30 ; 60.55', '579 ; 43.0', '1.475 ; 76.79', '958,03 ; 87.252', '370 ; 44.8', '1.500 ; 77.93', '360 ; 16.15', '2.287,80 ; 125.0', '464,69 ; 24.25', '1.340 ; 67.0', '968 ; 88.0', '535 ; 53.0', '894 ; 66.15', '3.490 ; 190.0', '1.299 ; 103.48', '945,84 ; 67.56', '2.349 ; 123.79', '1.015,13 ; 69.0', '799 ; 71.2', '840 ; 71.98', '699 ; 56.98', '320 ; 78.88', '1.132,37 ; 66.61', '1.577,76 ; 93.97', '460 ; 68.6', '1.130 ; 82.27', '791,62 ; 29.68', '1.693,63 ; 94.3', '1.249 ; 31.8', '1.551,16 ; 119.32', '2.175 ; 160.0', '900 ; 50.35', '1.700 ; 124.36', '1.675,17 ; 100.49', '376,50 ; 20.5', '1.550 ; 68.5', '944 ; 75.51', '1.789 ; 176.98', '1.142,09 ; 95.02', '2.900 ; 152.0', '1.211,42 ; 71.26', '520 ; 65.03', '928,32 ; 71.63', '975 ; 75.0', '750 ; 23.0', '350,11 ; 54.13', '1.324 ; 60.0', '584,95 ; 72.09', '1.323,20 ; 66.16', '2.004,13 ; 117.89', '571 ; 56.68', '1.378,72 ; 98.48', '1.490 ; 85.0', '1.623,05 ; 109.0', '447,18 ; 57.7', '1.207 ; 46.75', '1.280 ; 95.22', '1.044,05 ; 96.1', '969 ; 75.49', '1.800 ; 92.0', '557,15 ; 55.0', '1.476 ; 123.0', '1.110 ; 57.0', '510 ; 68.63', '732,07 ; 77.88', '1.500 ; 70.0', '1.150 ; 52.5', '1.450 ; 98.0', '443,37 ; 65.38', '1.336,82 ; 87.58', '1.727,23 ; 105.36', '438,60 ; 63.29', '845 ; 67.53', '854 ; 72.33', '453,56 ; 38.05', '599 ; 45.73', '1.081 ; 92.0', '1.485 ; 89.69', '650 ; 78.29', '650 ; 65.0', '279,44 ; 34.93', '899 ; 91.11', '599 ; 42.18', '364,88 ; 51.83', '1.550 ; 64.0', '2.720 ; 68.0', '1.558,26 ; 115.91', '860 ; 55.79', '669 ; 69.79', '900 ; 84.0', '595 ; 56.0', '1.065 ; 65.36', '1.050 ; 67.0', '1.430 ; 76.27', '779 ; 67.99', '1.236 ; 85.0', '3.500 ; 390.0', '1.293 ; 58.77', '851,24 ; 27.75', '3.058,60 ; 203.1', '1.149 ; 33.01', '865 ; 72.35', '876,18 ; 83.82', '244,04 ; 41.11', '1.197,27 ; 67.6', '1.149 ; 32.17', '1.435,07 ; 78.85', '1.027,15 ; 87.81', '424 ; 58.75', '1.188,49 ; 152.37', '1.279,16 ; 113.1', '1.690 ; 71.0', '675 ; 60.16', '1.930 ; 93.2', '1.078,52 ; 58.62', '1.545 ; 82.94', '1.199 ; 58.0', '790 ; 30.0', '950 ; 75.0', '655,20 ; 60.0', '1.595 ; 89.75', '674 ; 56.0', '859 ; 72.33', '850 ; 45.0', '700 ; 65.0', '472,58 ; 38.05', '1.615 ; 92.37', '1.203,31 ; 65.72', '391,21 ; 53.59', '1.733,59 ; 95.2', '499 ; 36.93', '1.720 ; 89.0', '1.290 ; 55.0', '880 ; 80.0', '870 ; 80.95', '2.400 ; 107.0', '789,50 ; 76.06', '1.200 ; 107.45', '895,95 ; 59.73', '1.477 ; 118.17', '257,14 ; 34.2', '3.000 ; 150.0', '1.200 ; 62.0', '879 ; 72.35', '799 ; 81.43', '459 ; 39.48', '699,24 ; 76.17', '539 ; 42.0', '647,73 ; 47.98', '560 ; 68.12', '1.520 ; 80.0', '598 ; 42.69', '240 ; 34.42', '1.093 ; 119.88', '1.271,25 ; 84.75', '1.595 ; 89.0', '2.330 ; 116.42', '1.085,04 ; 60.28', '550 ; 47.0', '1.281,55 ; 90.0', '2.504,74 ; 173.94', '390 ; 58.0', '1.100 ; 63.0', '949 ; 89.74', '3.850 ; 209.0', '660 ; 80.07', '862 ; 72.33', '1.246,28 ; 95.03', '1.840,57 ; 119.44', '1.650 ; 77.0', '1.399 ; 115.02', '1.400 ; 82.0', '1.094,80 ; 64.4', '420 ; 57.42', '1.699,37 ; 95.47', '1.698 ; 150.0', '969 ; 88.55', '1.670 ; 123.86', '982,22 ; 85.54', '1.660 ; 84.0', '729 ; 70.74', '622 ; 26.0', '1.756 ; 99.83', '640 ; 90.8', '1.355 ; 70.64', '1.121,58 ; 83.08', '441 ; 62.88', '278,12 ; 27.0', '1.360 ; 64.81', '562,05 ; 37.47', '1.571,81 ; 96.43', '1.980 ; 110.0', '819 ; 67.99', '570 ; 63.75', '2.920 ; 132.0', '680 ; 61.96', '1.160 ; 45.0', '689 ; 54.44', '819 ; 81.3', '505,63 ; 69.36', '949 ; 88.55', '900 ; 48.0', '700 ; 40.0', '2.104,17 ; 217.0', '940 ; 67.66', '2.990 ; 130.0', '790 ; 88.0', '1.738 ; 89.86', '1.149 ; 32.94', '915,19 ; 80.99', '540,13 ; 24.95', '1.490 ; 77.0', '1.636,73 ; 95.08', '924,03 ; 71.63', '740 ; 28.0', '1.843,16 ; 83.78', '450 ; 62.0', '987 ; 94.0', '2.197 ; 121.0', '1.384 ; 80.0', '589,71 ; 71.48', '629 ; 54.5', '2.300 ; 111.4', '1.872,60 ; 124.84', '1.014,80 ; 76.81', '729 ; 28.9', '1.580,67 ; 146.63', '1.556,88 ; 98.04', '1.342 ; 92.5', '2.190 ; 112.27', '610 ; 67.78', '599,16 ; 54.15', '698,29 ; 56.45', '1.210 ; 82.0', '1.659,67 ; 96.83', '1.085,04 ; 86.5', '1.100 ; 46.0', '1.999 ; 135.0', '250 ; 37.0', '5.309,75 ; 212.39', '799 ; 76.42', '1.410,72 ; 90.24', '3.500 ; 143.22', '291,21 ; 44.05', '999 ; 80.59', '910,92 ; 79.21', '735,84 ; 53.0', '1.749 ; 120.0', '390 ; 54.74', '2.000 ; 91.0', '882,35 ; 121.0', '3.264 ; 167.36', '769 ; 70.68', '3.915 ; 3.', '2.491 ; 99.65', '1.211,08 ; 93.16', '3.262 ; 195.0', '1.254,32 ; 74.25', '280 ; 33.99', '830,50 ; 75.5', '5.000 ; 200.0', '900 ; 81.11', '1.544 ; 72.64', '777 ; 105.0', '1.424 ; 89.0', '460 ; 67.53', '890 ; 30.0', '1.178,85 ; 40.65', '960 ; 60.0', '586,50 ; 69.0', '859,92 ; 48.31', '2.950 ; 164.0', '800 ; 29.0', '1.393,77 ; 87.11', '1.049 ; 96.44', '904,88 ; 73.33', '1.200 ; 120.0', '1.455,46 ; 84.62', '778,50 ; 25.95', '557,63 ; 23.75', '786,07 ; 30.79', '879 ; 77.09', '739 ; 52.62', '1.100 ; 93.61', '1.250 ; 52.08', '1.653 ; 87.0', '1.360 ; 66.69', '1.750,48 ; 100.66', '1.648,58 ; 72.47', '1.040 ; 65.48', '820 ; 23.0', '1.999,23 ; 101.69', '3.121,89 ; 143.54', '1.139,04 ; 81.36', '726,51 ; 56.45', '1.155 ; 101.5', '500,92 ; 74.36', '897 ; 66.35', '2.374 ; 172.0', '1.951,08 ; 111.49', '422 ; 76.3', '1.825 ; 126.82', '1.249 ; 33.21', '998,16 ; 83.18', '1.250 ; 56.61', '4.416,40 ; 110.41', '1.648,43 ; 95.34', '1.165 ; 65.6', '700 ; 53.23', '1.000 ; 100.0', '999 ; 90.94', '1.899 ; 130.78', '1.692,92 ; 98.77', '1.114 ; 85.22', '904,50 ; 67.0', '5.540,64 ; 131.92', '1.739,09 ; 96.67', '1.048,53 ; 96.55', '1.998,98 ; 121.15', '764,64 ; 53.0', '1.110,10 ; 65.3', '799 ; 82.15', '899 ; 76.15', '1.073,77 ; 85.69', '1.149 ; 93.48', '1.637,91 ; 98.02', '1.250 ; 61.0', '599 ; 65.31', '739,44 ; 72.0', '2.495 ; 166.34', '795 ; 30.0', '1.350 ; 110.73', '585 ; 65.0', '1.534 ; 77.66', '670 ; 30.0', '690 ; 41.0', '910 ; 68.33', '1.227 ; 62.77', '3.199 ; 156.1', '650 ; 40.0', '265 ; 11.0', '700,76 ; 56.65', '480 ; 23.5', '703,23 ; 56.85', '888,44 ; 63.46', '695,81 ; 56.25', '1.394,10 ; 92.94', '699 ; 49.0', '1.481,77 ; 106.22', '310 ; 44.0', '1.790 ; 113.0', '530 ; 57.71', '500 ; 24.95', '1.115 ; 104.01', '350 ; 29.19', '934,50 ; 89.0', '2.730 ; 120.06', '440 ; 72.81', '850 ; 35.0', '749 ; 74.15', '1.440 ; 47.0', '454 ; 66.32', '946,12 ; 67.58', '1.200 ; 99.29', '1.850 ; 107.0', '761,46 ; 74.0', '254,19 ; 36.27', '510 ; 68.12', '789,02 ; 73.87', '1.178 ; 68.71', '815 ; 84.0', '400 ; 45.0', '852,23 ; 27.55', '1.420 ; 84.4', '1.120 ; 56.0', '1.169,14 ; 82.045', '2.635,54 ; 241.0', '315,30 ; 49.98', '3.500 ; 158.0', '1.059 ; 81.5', '407 ; 57.0', '464 ; 58.0', '1.425 ; 80.72', '1.850 ; 91.0', '1.944,38 ; 127.5', '489,42 ; 58.51', '366,50 ; 20.5', '1.440 ; 104.52', '750 ; 88.63', '680 ; 37.11', '330 ; 30.0', '1.170 ; 88.61', '757,32 ; 81.58', '2.720 ; 136.15', '470 ; 81.0', '750 ; 1376.0', '1.300 ; 70.0', '1.584 ; 126.7', '784,10 ; 62.23', '1.000 ; 83.7', '1.183,54 ; 69.62', '4.360 ; 172.0', '530 ; 20.5', '433,62 ; 60.72', '1.995 ; 99.78', '852,77 ; 27.45', '1.443 ; 84.78', '1.199 ; 90.66', '940 ; 42.29', '594 ; 66.0', '5.981 ; 225.0', '2.800 ; 174.93', '1.126,14 ; 98.0', '901,51 ; 53.03', '1.289,47 ; 100.53', '1.149 ; 30.77', '790 ; 82.0', '1.270 ; 106.0', '1.039 ; 41.56', '640 ; 102.97', '1.310 ; 93.4', '510 ; 64.19', '822 ; 59.0', '1.650 ; 73.0']

The list above shows how messy the dataset looks like with both prices and sizes of various apartments mapped to each other with a semi colon, and we can easily visualize the whitespaces, and class of all numbers being strings which will evidently affect any aggregation purpose. Now its time to refine the Datasets, firstly we need to partition prices from sizes.

In [8]:
refined_price = []
for price in rough_list:
    refined_price.append(price.rpartition(";")[0])
print(refined_price)

['470 ', '720 ', '1.870 ', '1.699,28 ', '879 ', '1.119,04 ', '656 ', '3.216,57 ', '401,58 ', '1.875 ', '1.091,70 ', '1.100 ', '1.890 ', '498,50 ', '3.181,10 ', '735 ', '2.141,64 ', '1.353 ', '1.157,90 ', '2.485 ', '420,40 ', '699 ', '2.864,67 ', '659,60 ', '1.123,20 ', '1.300 ', '949 ', '659 ', '1.005,35 ', '629 ', '415,50 ', '1.900 ', '2.900 ', '850 ', '852,93 ', '1.700 ', '997,50 ', '1.020 ', '1.335,71 ', '1.400 ', '2.175 ', '437,18 ', '1.450 ', '1.600 ', '1.000 ', '599 ', '1.535 ', '723,94 ', '558,11 ', '900 ', '649 ', '670 ', '734,75 ', '790,65 ', '700 ', '598 ', '1.568 ', '430 ', '900 ', '600 ', '1.150 ', '1.677 ', '994 ', '254,34 ', '352 ', '1.400 ', '1.650 ', '901,77 ', '950 ', '726 ', '3.475 ', '1.136,68 ', '1.460,98 ', '1.484,18 ', '1.412,95 ', '712,68 ', '799 ', '1.150 ', '987 ', '687,22 ', '750 ', '699 ', '791,22 ', '1.875 ', '1.350 ', '1.125 ', '707 ', '1.249 ', '1.249 ', '1.330,44 ', '9.500 ', '1.542,87 ', '1.484,98 ', '532,17 ', '1.567,43 ', '644,10 ', '499 ', '550 ', '2.275 ', '606 ', '912,49 ', '874,46 ', '690,91 ', '218,41 ', '2.815 ', '2.440 ', '520 ', '2.305,02 ', '540 ', '1.450 ', '1.496,06 ', '1.190 ', '449 ', '1.559,01 ', '1.654,15 ', '1.480 ', '5.700 ', '1.199 ', '848,34 ', '955 ', '1.646,09 ', '578,16 ', '1.719,32 ', '1.158,95 ', '1.550 ', '1.196,62 ', '2.146,38 ', '1.149 ', '719 ', '800 ', '1.553,89 ', '1.460 ', '1.907,17 ', '1.250 ', '1.270 ', '1.419 ', '1.210 ', '259,94 ', '1.650 ', '1.941,94 ', '903 ', '1.270 ', '1.663,47 ', '1.584 ', '950 ', '640 ', '746,10 ', '3.265,42 ', '1.800 ', '1.901,50 ', '1.590 ', '1.545 ', '584,40 ', '949 ', '1.019,16 ', '990 ', '1.840 ', '268 ', '902,48 ', '649 ', '790,97 ', '1.285 ', '936,99 ', '1.295,53 ', '1.471,63 ', '650 ', '1.450 ', '2.759 ', '473,24 ', '1.207 ', '460 ', '856,06 ', '699 ', '491,88 ', '1.992 ', '1.150 ', '761,25 ', '2.150 ', '1.950 ', '876,79 ', '638,55 ', '1.289 ', '1.800 ', '549 ', '965 ', '613,41 ', '781,50 ', '1.450,44 ', '1.190,95 ', '1.072,53 ', '888 ', '885 ', '600 ', '1.050 ', '1.809,22 ', '2.053,50 ', '1.185 ', '477,33 ', '3.800 ', '449 ', '1.020 ', '1.487,50 ', '320 ', '780 ', '1.344,87 ', '770 ', '850 ', '2.600 ', '819 ', '1.380 ', '1.598,67 ', '1.295 ', '897 ', '1.261,50 ', '472,83 ', '1.310 ', '799 ', '538 ', '1.571,40 ', '1.218,92 ', '1.190 ', '739 ', '1.405 ', '4.200 ', '288,80 ', '1.400 ', '1.000 ', '844,25 ', '3.111 ', '420 ', '1.625 ', '515,77 ', '459 ', '840,15 ', '5.100 ', '1.299 ', '1.520 ', '980 ', '1.314,12 ', '1.195 ', '630 ', '1.050 ', '970,68 ', '1.600 ', '4.732 ', '1.249 ', '792,99 ', '370 ', '442,33 ', '1.330,85 ', '1.942,50 ', '1.067,89 ', '364,76 ', '631,80 ', '1.525 ', '1.699,30 ', '1.181 ', '579 ', '1.491,66 ', '294,20 ', '800 ', '719 ', '494,22 ', '281,50 ', '1.200 ', '1.018,50 ', '1.200 ', '380 ', '935 ', '890 ', '979 ', '773 ', '769 ', '557 ', '2.299 ', '980 ', '1.148 ', '725 ', '518,82 ', '1.486,52 ', '856,04 ', '293 ', '500 ', '979,53 ', '1.249 ', '936 ', '950 ', '499 ', '1.450 ', '630,23 ', '1.200 ', '375,38 ', '810 ', '1.878 ', '1.020 ', '2.000 ', '1.693,85 ', '1.350 ', '1.200 ', '1.270,58 ', '949 ', '2.145 ', '1.435 ', '2.100 ', '1.869,90 ', '475 ', '2.750 ', '673,71 ', '350 ', '633,33 ', '1.149 ', '1.132,34 ', '649 ', '1.100 ', '2.300 ', '1.545 ', '550 ', '1.635,26 ', '673,92 ', '440 ', '449 ', '600 ', '2.500 ', '1.117,50 ', '1.300 ', '2.250 ', '839,29 ', '1.478 ', '2.448 ', '1.069,81 ', '4.360 ', '2.019,68 ', '491 ', '1.023,30 ', '579 ', '1.475 ', '958,03 ', '370 ', '1.500 ', '360 ', '2.287,80 ', '464,69 ', '1.340 ', '968 ', '535 ', '894 ', '3.490 ', '1.299 ', '945,84 ', '2.349 ', '1.015,13 ', '799 ', '840 ', '699 ', '320 ', '1.132,37 ', '1.577,76 ', '460 ', '1.130 ', '791,62 ', '1.693,63 ', '1.249 ', '1.551,16 ', '2.175 ', '900 ', '1.700 ', '1.675,17 ', '376,50 ', '1.550 ', '944 ', '1.789 ', '1.142,09 ', '2.900 ', '1.211,42 ', '520 ', '928,32 ', '975 ', '750 ', '350,11 ', '1.324 ', '584,95 ', '1.323,20 ', '2.004,13 ', '571 ', '1.378,72 ', '1.490 ', '1.623,05 ', '447,18 ', '1.207 ', '1.280 ', '1.044,05 ', '969 ', '1.800 ', '557,15 ', '1.476 ', '1.110 ', '510 ', '732,07 ', '1.500 ', '1.150 ', '1.450 ', '443,37 ', '1.336,82 ', '1.727,23 ', '438,60 ', '845 ', '854 ', '453,56 ', '599 ', '1.081 ', '1.485 ', '650 ', '650 ', '279,44 ', '899 ', '599 ', '364,88 ', '1.550 ', '2.720 ', '1.558,26 ', '860 ', '669 ', '900 ', '595 ', '1.065 ', '1.050 ', '1.430 ', '779 ', '1.236 ', '3.500 ', '1.293 ', '851,24 ', '3.058,60 ', '1.149 ', '865 ', '876,18 ', '244,04 ', '1.197,27 ', '1.149 ', '1.435,07 ', '1.027,15 ', '424 ', '1.188,49 ', '1.279,16 ', '1.690 ', '675 ', '1.930 ', '1.078,52 ', '1.545 ', '1.199 ', '790 ', '950 ', '655,20 ', '1.595 ', '674 ', '859 ', '850 ', '700 ', '472,58 ', '1.615 ', '1.203,31 ', '391,21 ', '1.733,59 ', '499 ', '1.720 ', '1.290 ', '880 ', '870 ', '2.400 ', '789,50 ', '1.200 ', '895,95 ', '1.477 ', '257,14 ', '3.000 ', '1.200 ', '879 ', '799 ', '459 ', '699,24 ', '539 ', '647,73 ', '560 ', '1.520 ', '598 ', '240 ', '1.093 ', '1.271,25 ', '1.595 ', '2.330 ', '1.085,04 ', '550 ', '1.281,55 ', '2.504,74 ', '390 ', '1.100 ', '949 ', '3.850 ', '660 ', '862 ', '1.246,28 ', '1.840,57 ', '1.650 ', '1.399 ', '1.400 ', '1.094,80 ', '420 ', '1.699,37 ', '1.698 ', '969 ', '1.670 ', '982,22 ', '1.660 ', '729 ', '622 ', '1.756 ', '640 ', '1.355 ', '1.121,58 ', '441 ', '278,12 ', '1.360 ', '562,05 ', '1.571,81 ', '1.980 ', '819 ', '570 ', '2.920 ', '680 ', '1.160 ', '689 ', '819 ', '505,63 ', '949 ', '900 ', '700 ', '2.104,17 ', '940 ', '2.990 ', '790 ', '1.738 ', '1.149 ', '915,19 ', '540,13 ', '1.490 ', '1.636,73 ', '924,03 ', '740 ', '1.843,16 ', '450 ', '987 ', '2.197 ', '1.384 ', '589,71 ', '629 ', '2.300 ', '1.872,60 ', '1.014,80 ', '729 ', '1.580,67 ', '1.556,88 ', '1.342 ', '2.190 ', '610 ', '599,16 ', '698,29 ', '1.210 ', '1.659,67 ', '1.085,04 ', '1.100 ', '1.999 ', '250 ', '5.309,75 ', '799 ', '1.410,72 ', '3.500 ', '291,21 ', '999 ', '910,92 ', '735,84 ', '1.749 ', '390 ', '2.000 ', '882,35 ', '3.264 ', '769 ', '3.915 ', '2.491 ', '1.211,08 ', '3.262 ', '1.254,32 ', '280 ', '830,50 ', '5.000 ', '900 ', '1.544 ', '777 ', '1.424 ', '460 ', '890 ', '1.178,85 ', '960 ', '586,50 ', '859,92 ', '2.950 ', '800 ', '1.393,77 ', '1.049 ', '904,88 ', '1.200 ', '1.455,46 ', '778,50 ', '557,63 ', '786,07 ', '879 ', '739 ', '1.100 ', '1.250 ', '1.653 ', '1.360 ', '1.750,48 ', '1.648,58 ', '1.040 ', '820 ', '1.999,23 ', '3.121,89 ', '1.139,04 ', '726,51 ', '1.155 ', '500,92 ', '897 ', '2.374 ', '1.951,08 ', '422 ', '1.825 ', '1.249 ', '998,16 ', '1.250 ', '4.416,40 ', '1.648,43 ', '1.165 ', '700 ', '1.000 ', '999 ', '1.899 ', '1.692,92 ', '1.114 ', '904,50 ', '5.540,64 ', '1.739,09 ', '1.048,53 ', '1.998,98 ', '764,64 ', '1.110,10 ', '799 ', '899 ', '1.073,77 ', '1.149 ', '1.637,91 ', '1.250 ', '599 ', '739,44 ', '2.495 ', '795 ', '1.350 ', '585 ', '1.534 ', '670 ', '690 ', '910 ', '1.227 ', '3.199 ', '650 ', '265 ', '700,76 ', '480 ', '703,23 ', '888,44 ', '695,81 ', '1.394,10 ', '699 ', '1.481,77 ', '310 ', '1.790 ', '530 ', '500 ', '1.115 ', '350 ', '934,50 ', '2.730 ', '440 ', '850 ', '749 ', '1.440 ', '454 ', '946,12 ', '1.200 ', '1.850 ', '761,46 ', '254,19 ', '510 ', '789,02 ', '1.178 ', '815 ', '400 ', '852,23 ', '1.420 ', '1.120 ', '1.169,14 ', '2.635,54 ', '315,30 ', '3.500 ', '1.059 ', '407 ', '464 ', '1.425 ', '1.850 ', '1.944,38 ', '489,42 ', '366,50 ', '1.440 ', '750 ', '680 ', '330 ', '1.170 ', '757,32 ', '2.720 ', '470 ', '750 ', '1.300 ', '1.584 ', '784,10 ', '1.000 ', '1.183,54 ', '4.360 ', '530 ', '433,62 ', '1.995 ', '852,77 ', '1.443 ', '1.199 ', '940 ', '594 ', '5.981 ', '2.800 ', '1.126,14 ', '901,51 ', '1.289,47 ', '1.149 ', '790 ', '1.270 ', '1.039 ', '640 ', '1.310 ', '510 ', '822 ', '1.650 ']

From the above list, we can see the price has been succesfully seperated away from the size, but as we can see, we still have a messy list of prices with the dot(.) notation signify the values is in its thousands and the coma(,) represent a decimal notation, However this can not help us with aggregation and it will be certain that we will not get our accuracy if we decide to sum up our prices for example. In addition , we also need to eradicate the white spaces.

In [9]:
price = []
for prices in refined_price:
    price.append(prices.replace(" ", "").replace(".", "").replace(",", "."))
print(price)

['470', '720', '1870', '1699.28', '879', '1119.04', '656', '3216.57', '401.58', '1875', '1091.70', '1100', '1890', '498.50', '3181.10', '735', '2141.64', '1353', '1157.90', '2485', '420.40', '699', '2864.67', '659.60', '1123.20', '1300', '949', '659', '1005.35', '629', '415.50', '1900', '2900', '850', '852.93', '1700', '997.50', '1020', '1335.71', '1400', '2175', '437.18', '1450', '1600', '1000', '599', '1535', '723.94', '558.11', '900', '649', '670', '734.75', '790.65', '700', '598', '1568', '430', '900', '600', '1150', '1677', '994', '254.34', '352', '1400', '1650', '901.77', '950', '726', '3475', '1136.68', '1460.98', '1484.18', '1412.95', '712.68', '799', '1150', '987', '687.22', '750', '699', '791.22', '1875', '1350', '1125', '707', '1249', '1249', '1330.44', '9500', '1542.87', '1484.98', '532.17', '1567.43', '644.10', '499', '550', '2275', '606', '912.49', '874.46', '690.91', '218.41', '2815', '2440', '520', '2305.02', '540', '1450', '1496.06', '1190', '449', '1559.01', '1654.15', '1480', '5700', '1199', '848.34', '955', '1646.09', '578.16', '1719.32', '1158.95', '1550', '1196.62', '2146.38', '1149', '719', '800', '1553.89', '1460', '1907.17', '1250', '1270', '1419', '1210', '259.94', '1650', '1941.94', '903', '1270', '1663.47', '1584', '950', '640', '746.10', '3265.42', '1800', '1901.50', '1590', '1545', '584.40', '949', '1019.16', '990', '1840', '268', '902.48', '649', '790.97', '1285', '936.99', '1295.53', '1471.63', '650', '1450', '2759', '473.24', '1207', '460', '856.06', '699', '491.88', '1992', '1150', '761.25', '2150', '1950', '876.79', '638.55', '1289', '1800', '549', '965', '613.41', '781.50', '1450.44', '1190.95', '1072.53', '888', '885', '600', '1050', '1809.22', '2053.50', '1185', '477.33', '3800', '449', '1020', '1487.50', '320', '780', '1344.87', '770', '850', '2600', '819', '1380', '1598.67', '1295', '897', '1261.50', '472.83', '1310', '799', '538', '1571.40', '1218.92', '1190', '739', '1405', '4200', '288.80', '1400', '1000', '844.25', '3111', '420', '1625', '515.77', '459', '840.15', '5100', '1299', '1520', '980', '1314.12', '1195', '630', '1050', '970.68', '1600', '4732', '1249', '792.99', '370', '442.33', '1330.85', '1942.50', '1067.89', '364.76', '631.80', '1525', '1699.30', '1181', '579', '1491.66', '294.20', '800', '719', '494.22', '281.50', '1200', '1018.50', '1200', '380', '935', '890', '979', '773', '769', '557', '2299', '980', '1148', '725', '518.82', '1486.52', '856.04', '293', '500', '979.53', '1249', '936', '950', '499', '1450', '630.23', '1200', '375.38', '810', '1878', '1020', '2000', '1693.85', '1350', '1200', '1270.58', '949', '2145', '1435', '2100', '1869.90', '475', '2750', '673.71', '350', '633.33', '1149', '1132.34', '649', '1100', '2300', '1545', '550', '1635.26', '673.92', '440', '449', '600', '2500', '1117.50', '1300', '2250', '839.29', '1478', '2448', '1069.81', '4360', '2019.68', '491', '1023.30', '579', '1475', '958.03', '370', '1500', '360', '2287.80', '464.69', '1340', '968', '535', '894', '3490', '1299', '945.84', '2349', '1015.13', '799', '840', '699', '320', '1132.37', '1577.76', '460', '1130', '791.62', '1693.63', '1249', '1551.16', '2175', '900', '1700', '1675.17', '376.50', '1550', '944', '1789', '1142.09', '2900', '1211.42', '520', '928.32', '975', '750', '350.11', '1324', '584.95', '1323.20', '2004.13', '571', '1378.72', '1490', '1623.05', '447.18', '1207', '1280', '1044.05', '969', '1800', '557.15', '1476', '1110', '510', '732.07', '1500', '1150', '1450', '443.37', '1336.82', '1727.23', '438.60', '845', '854', '453.56', '599', '1081', '1485', '650', '650', '279.44', '899', '599', '364.88', '1550', '2720', '1558.26', '860', '669', '900', '595', '1065', '1050', '1430', '779', '1236', '3500', '1293', '851.24', '3058.60', '1149', '865', '876.18', '244.04', '1197.27', '1149', '1435.07', '1027.15', '424', '1188.49', '1279.16', '1690', '675', '1930', '1078.52', '1545', '1199', '790', '950', '655.20', '1595', '674', '859', '850', '700', '472.58', '1615', '1203.31', '391.21', '1733.59', '499', '1720', '1290', '880', '870', '2400', '789.50', '1200', '895.95', '1477', '257.14', '3000', '1200', '879', '799', '459', '699.24', '539', '647.73', '560', '1520', '598', '240', '1093', '1271.25', '1595', '2330', '1085.04', '550', '1281.55', '2504.74', '390', '1100', '949', '3850', '660', '862', '1246.28', '1840.57', '1650', '1399', '1400', '1094.80', '420', '1699.37', '1698', '969', '1670', '982.22', '1660', '729', '622', '1756', '640', '1355', '1121.58', '441', '278.12', '1360', '562.05', '1571.81', '1980', '819', '570', '2920', '680', '1160', '689', '819', '505.63', '949', '900', '700', '2104.17', '940', '2990', '790', '1738', '1149', '915.19', '540.13', '1490', '1636.73', '924.03', '740', '1843.16', '450', '987', '2197', '1384', '589.71', '629', '2300', '1872.60', '1014.80', '729', '1580.67', '1556.88', '1342', '2190', '610', '599.16', '698.29', '1210', '1659.67', '1085.04', '1100', '1999', '250', '5309.75', '799', '1410.72', '3500', '291.21', '999', '910.92', '735.84', '1749', '390', '2000', '882.35', '3264', '769', '3915', '2491', '1211.08', '3262', '1254.32', '280', '830.50', '5000', '900', '1544', '777', '1424', '460', '890', '1178.85', '960', '586.50', '859.92', '2950', '800', '1393.77', '1049', '904.88', '1200', '1455.46', '778.50', '557.63', '786.07', '879', '739', '1100', '1250', '1653', '1360', '1750.48', '1648.58', '1040', '820', '1999.23', '3121.89', '1139.04', '726.51', '1155', '500.92', '897', '2374', '1951.08', '422', '1825', '1249', '998.16', '1250', '4416.40', '1648.43', '1165', '700', '1000', '999', '1899', '1692.92', '1114', '904.50', '5540.64', '1739.09', '1048.53', '1998.98', '764.64', '1110.10', '799', '899', '1073.77', '1149', '1637.91', '1250', '599', '739.44', '2495', '795', '1350', '585', '1534', '670', '690', '910', '1227', '3199', '650', '265', '700.76', '480', '703.23', '888.44', '695.81', '1394.10', '699', '1481.77', '310', '1790', '530', '500', '1115', '350', '934.50', '2730', '440', '850', '749', '1440', '454', '946.12', '1200', '1850', '761.46', '254.19', '510', '789.02', '1178', '815', '400', '852.23', '1420', '1120', '1169.14', '2635.54', '315.30', '3500', '1059', '407', '464', '1425', '1850', '1944.38', '489.42', '366.50', '1440', '750', '680', '330', '1170', '757.32', '2720', '470', '750', '1300', '1584', '784.10', '1000', '1183.54', '4360', '530', '433.62', '1995', '852.77', '1443', '1199', '940', '594', '5981', '2800', '1126.14', '901.51', '1289.47', '1149', '790', '1270', '1039', '640', '1310', '510', '822', '1650']

From the operation we performed above, we can see now that the pattern of our prices seems to be getting more readable now after the whitespaces has been taking out, after replacing the coma(,) with the dot(.) notation and taking out the dot(.) notation at the front so we can have a more represented prices that accept an accurate aggregation. However, we still need to strip off the string assigned to our prices because we can't aggregate a string class. On that basis we have to convert all price to float.

In [11]:
final_price_list = []
for price_in_string_class in price:
    final_price_list.append(float(price_in_string_class))
print(final_price_list)

[470.0, 720.0, 1870.0, 1699.28, 879.0, 1119.04, 656.0, 3216.57, 401.58, 1875.0, 1091.7, 1100.0, 1890.0, 498.5, 3181.1, 735.0, 2141.64, 1353.0, 1157.9, 2485.0, 420.4, 699.0, 2864.67, 659.6, 1123.2, 1300.0, 949.0, 659.0, 1005.35, 629.0, 415.5, 1900.0, 2900.0, 850.0, 852.93, 1700.0, 997.5, 1020.0, 1335.71, 1400.0, 2175.0, 437.18, 1450.0, 1600.0, 1000.0, 599.0, 1535.0, 723.94, 558.11, 900.0, 649.0, 670.0, 734.75, 790.65, 700.0, 598.0, 1568.0, 430.0, 900.0, 600.0, 1150.0, 1677.0, 994.0, 254.34, 352.0, 1400.0, 1650.0, 901.77, 950.0, 726.0, 3475.0, 1136.68, 1460.98, 1484.18, 1412.95, 712.68, 799.0, 1150.0, 987.0, 687.22, 750.0, 699.0, 791.22, 1875.0, 1350.0, 1125.0, 707.0, 1249.0, 1249.0, 1330.44, 9500.0, 1542.87, 1484.98, 532.17, 1567.43, 644.1, 499.0, 550.0, 2275.0, 606.0, 912.49, 874.46, 690.91, 218.41, 2815.0, 2440.0, 520.0, 2305.02, 540.0, 1450.0, 1496.06, 1190.0, 449.0, 1559.01, 1654.15, 1480.0, 5700.0, 1199.0, 848.34, 955.0, 1646.09, 578.16, 1719.32, 1158.95, 1550.0, 1196.62, 2146.38, 1149.0, 719.0, 800.0, 1553.89, 1460.0, 1907.17, 1250.0, 1270.0, 1419.0, 1210.0, 259.94, 1650.0, 1941.94, 903.0, 1270.0, 1663.47, 1584.0, 950.0, 640.0, 746.1, 3265.42, 1800.0, 1901.5, 1590.0, 1545.0, 584.4, 949.0, 1019.16, 990.0, 1840.0, 268.0, 902.48, 649.0, 790.97, 1285.0, 936.99, 1295.53, 1471.63, 650.0, 1450.0, 2759.0, 473.24, 1207.0, 460.0, 856.06, 699.0, 491.88, 1992.0, 1150.0, 761.25, 2150.0, 1950.0, 876.79, 638.55, 1289.0, 1800.0, 549.0, 965.0, 613.41, 781.5, 1450.44, 1190.95, 1072.53, 888.0, 885.0, 600.0, 1050.0, 1809.22, 2053.5, 1185.0, 477.33, 3800.0, 449.0, 1020.0, 1487.5, 320.0, 780.0, 1344.87, 770.0, 850.0, 2600.0, 819.0, 1380.0, 1598.67, 1295.0, 897.0, 1261.5, 472.83, 1310.0, 799.0, 538.0, 1571.4, 1218.92, 1190.0, 739.0, 1405.0, 4200.0, 288.8, 1400.0, 1000.0, 844.25, 3111.0, 420.0, 1625.0, 515.77, 459.0, 840.15, 5100.0, 1299.0, 1520.0, 980.0, 1314.12, 1195.0, 630.0, 1050.0, 970.68, 1600.0, 4732.0, 1249.0, 792.99, 370.0, 442.33, 1330.85, 1942.5, 1067.89, 364.76, 631.8, 1525.0, 1699.3, 1181.0, 579.0, 1491.66, 294.2, 800.0, 719.0, 494.22, 281.5, 1200.0, 1018.5, 1200.0, 380.0, 935.0, 890.0, 979.0, 773.0, 769.0, 557.0, 2299.0, 980.0, 1148.0, 725.0, 518.82, 1486.52, 856.04, 293.0, 500.0, 979.53, 1249.0, 936.0, 950.0, 499.0, 1450.0, 630.23, 1200.0, 375.38, 810.0, 1878.0, 1020.0, 2000.0, 1693.85, 1350.0, 1200.0, 1270.58, 949.0, 2145.0, 1435.0, 2100.0, 1869.9, 475.0, 2750.0, 673.71, 350.0, 633.33, 1149.0, 1132.34, 649.0, 1100.0, 2300.0, 1545.0, 550.0, 1635.26, 673.92, 440.0, 449.0, 600.0, 2500.0, 1117.5, 1300.0, 2250.0, 839.29, 1478.0, 2448.0, 1069.81, 4360.0, 2019.68, 491.0, 1023.3, 579.0, 1475.0, 958.03, 370.0, 1500.0, 360.0, 2287.8, 464.69, 1340.0, 968.0, 535.0, 894.0, 3490.0, 1299.0, 945.84, 2349.0, 1015.13, 799.0, 840.0, 699.0, 320.0, 1132.37, 1577.76, 460.0, 1130.0, 791.62, 1693.63, 1249.0, 1551.16, 2175.0, 900.0, 1700.0, 1675.17, 376.5, 1550.0, 944.0, 1789.0, 1142.09, 2900.0, 1211.42, 520.0, 928.32, 975.0, 750.0, 350.11, 1324.0, 584.95, 1323.2, 2004.13, 571.0, 1378.72, 1490.0, 1623.05, 447.18, 1207.0, 1280.0, 1044.05, 969.0, 1800.0, 557.15, 1476.0, 1110.0, 510.0, 732.07, 1500.0, 1150.0, 1450.0, 443.37, 1336.82, 1727.23, 438.6, 845.0, 854.0, 453.56, 599.0, 1081.0, 1485.0, 650.0, 650.0, 279.44, 899.0, 599.0, 364.88, 1550.0, 2720.0, 1558.26, 860.0, 669.0, 900.0, 595.0, 1065.0, 1050.0, 1430.0, 779.0, 1236.0, 3500.0, 1293.0, 851.24, 3058.6, 1149.0, 865.0, 876.18, 244.04, 1197.27, 1149.0, 1435.07, 1027.15, 424.0, 1188.49, 1279.16, 1690.0, 675.0, 1930.0, 1078.52, 1545.0, 1199.0, 790.0, 950.0, 655.2, 1595.0, 674.0, 859.0, 850.0, 700.0, 472.58, 1615.0, 1203.31, 391.21, 1733.59, 499.0, 1720.0, 1290.0, 880.0, 870.0, 2400.0, 789.5, 1200.0, 895.95, 1477.0, 257.14, 3000.0, 1200.0, 879.0, 799.0, 459.0, 699.24, 539.0, 647.73, 560.0, 1520.0, 598.0, 240.0, 1093.0, 1271.25, 1595.0, 2330.0, 1085.04, 550.0, 1281.55, 2504.74, 390.0, 1100.0, 949.0, 3850.0, 660.0, 862.0, 1246.28, 1840.57, 1650.0, 1399.0, 1400.0, 1094.8, 420.0, 1699.37, 1698.0, 969.0, 1670.0, 982.22, 1660.0, 729.0, 622.0, 1756.0, 640.0, 1355.0, 1121.58, 441.0, 278.12, 1360.0, 562.05, 1571.81, 1980.0, 819.0, 570.0, 2920.0, 680.0, 1160.0, 689.0, 819.0, 505.63, 949.0, 900.0, 700.0, 2104.17, 940.0, 2990.0, 790.0, 1738.0, 1149.0, 915.19, 540.13, 1490.0, 1636.73, 924.03, 740.0, 1843.16, 450.0, 987.0, 2197.0, 1384.0, 589.71, 629.0, 2300.0, 1872.6, 1014.8, 729.0, 1580.67, 1556.88, 1342.0, 2190.0, 610.0, 599.16, 698.29, 1210.0, 1659.67, 1085.04, 1100.0, 1999.0, 250.0, 5309.75, 799.0, 1410.72, 3500.0, 291.21, 999.0, 910.92, 735.84, 1749.0, 390.0, 2000.0, 882.35, 3264.0, 769.0, 3915.0, 2491.0, 1211.08, 3262.0, 1254.32, 280.0, 830.5, 5000.0, 900.0, 1544.0, 777.0, 1424.0, 460.0, 890.0, 1178.85, 960.0, 586.5, 859.92, 2950.0, 800.0, 1393.77, 1049.0, 904.88, 1200.0, 1455.46, 778.5, 557.63, 786.07, 879.0, 739.0, 1100.0, 1250.0, 1653.0, 1360.0, 1750.48, 1648.58, 1040.0, 820.0, 1999.23, 3121.89, 1139.04, 726.51, 1155.0, 500.92, 897.0, 2374.0, 1951.08, 422.0, 1825.0, 1249.0, 998.16, 1250.0, 4416.4, 1648.43, 1165.0, 700.0, 1000.0, 999.0, 1899.0, 1692.92, 1114.0, 904.5, 5540.64, 1739.09, 1048.53, 1998.98, 764.64, 1110.1, 799.0, 899.0, 1073.77, 1149.0, 1637.91, 1250.0, 599.0, 739.44, 2495.0, 795.0, 1350.0, 585.0, 1534.0, 670.0, 690.0, 910.0, 1227.0, 3199.0, 650.0, 265.0, 700.76, 480.0, 703.23, 888.44, 695.81, 1394.1, 699.0, 1481.77, 310.0, 1790.0, 530.0, 500.0, 1115.0, 350.0, 934.5, 2730.0, 440.0, 850.0, 749.0, 1440.0, 454.0, 946.12, 1200.0, 1850.0, 761.46, 254.19, 510.0, 789.02, 1178.0, 815.0, 400.0, 852.23, 1420.0, 1120.0, 1169.14, 2635.54, 315.3, 3500.0, 1059.0, 407.0, 464.0, 1425.0, 1850.0, 1944.38, 489.42, 366.5, 1440.0, 750.0, 680.0, 330.0, 1170.0, 757.32, 2720.0, 470.0, 750.0, 1300.0, 1584.0, 784.1, 1000.0, 1183.54, 4360.0, 530.0, 433.62, 1995.0, 852.77, 1443.0, 1199.0, 940.0, 594.0, 5981.0, 2800.0, 1126.14, 901.51, 1289.47, 1149.0, 790.0, 1270.0, 1039.0, 640.0, 1310.0, 510.0, 822.0, 1650.0]

Now we can see our price list has been refined to a well structured and lot readable, however we can decide to convert soem prices to an integer but it doesn't make any difference if we decided to conduct some aggregation, so in this case we can leave all as float and create a DataFrame for price list using the pd.DataFrame in-built function in pandas.

In [13]:
price_df = pd.DataFrame(final_price_list)

In [14]:
price_df.head()

         0
0   470.00
1   720.00
2  1870.00
3  1699.28
4   879.00

In [15]:
rough_size = []
for sizes in rough_list:
    rough_size.append(sizes[-6:])
print(rough_size)

[' 56.85', ' 95.13', '; 75.0', '108.58', '; 64.0', ' 69.94', '; 52.5', ' 185.5', ' 57.62', '126.78', '; 96.1', '; 53.0', '147.36', ' 33.21', ' 212.1', ' 59.37', '134.02', ' 123.0', '; 99.2', ' 99.39', '; 42.4', ' 70.28', '144.17', ' 65.96', '; 35.1', '; 42.5', '; 88.3', ' 58.07', '101.55', '; 54.8', '; 42.0', ' 116.0', ' 132.0', ' 95.95', '; 66.9', '; 90.0', ' 105.0', ' 29.13', ' 113.1', '; 74.0', '119.85', ' 53.26', '; 88.0', ' 105.0', '; 53.7', ' 53.74', ' 87.81', ' 56.25', ' 23.86', '; 62.0', ' 22.35', '; 54.6', ' 59.35', ' 29.87', '; 41.0', ' 46.02', '; 98.0', ' 58.55', '; 91.0', '; 67.0', ' 115.0', ' 140.0', '; 83.0', ' 39.13', '; 57.7', ' 72.55', '103.33', ' 66.29', '; 80.0', ' 65.76', ' 178.4', '; 72.4', '; 74.5', ' 98.43', '97.445', ' 59.39', ' 73.26', '; 81.0', '; 93.0', ' 60.23', '; 50.0', ' 57.35', ' 29.76', '117.23', ' 104.0', ' 83.37', ' 74.38', '; 43.0', ' 31.97', ' 53.23', ' 400.0', ' 91.57', ' 86.79', ' 89.44', '129.54', ' 64.41', '; 37.1', '; 20.5', ' 182.0', ' 62.38', '; 54.9', '; 76.0', '; 48.0', ' 36.29', '102.36', ' 130.0', '; 58.0', '171.76', '; 20.5', '0 ; 1.', ' 90.67', ' 85.27', ' 33.54', '102.23', ' 95.23', '102.56', ' 186.0', ' 93.93', ' 60.38', '; 56.0', ' 94.17', ' 72.27', ' 99.44', ' 89.15', ' 77.79', '157.45', '122.65', '; 31.9', ' 73.97', '; 75.0', '; 88.0', ' 64.86', ' 98.67', '; 78.0', '; 79.2', ' 129.0', '115.39', ' 30.59', ' 126.7', '122.83', '; 64.5', ' 43.71', ' 98.43', ' 91.84', ' 47.63', ' 54.12', ' 49.74', '143.54', '; 96.6', ' 86.42', ' 86.55', ' 91.86', ' 59.03', ' 29.95', '; 85.0', '; 90.0', ' 108.0', '; 15.0', ' 66.85', ' 70.68', ' 68.78', '171.06', ' 74.07', '; 69.1', '; 96.5', '; 49.0', ' 131.0', '141.32', ' 60.75', '; 46.5', ' 68.54', ' 26.79', '; 36.0', ' 68.88', '; 60.0', '; 50.0', ' 101.5', '; 93.2', ' 104.0', ' 73.31', ' 58.05', ' 101.0', '; 82.5', ' 41.42', ' 60.98', ' 53.34', ' 71.04', ' 85.12', ' 94.52', ' 63.09', ' 78.95', '; 59.0', ' 67.88', '; 65.0', ' 95.98', ' 136.9', '; 86.0', ' 64.33', ' 158.0', ' 35.69', ' 42.29', '; 87.5', ' 43.68', '; 39.0', ' 99.62', ' 94.21', '; 95.1', ' 130.0', ' 86.03', '110.72', '103.14', '122.67', ' 44.87', ' 63.17', ' 62.96', '; 43.1', ' 71.41', ' 19.34', '; 87.3', ' 90.29', ' 88.61', ' 78.24', ' 79.33', ' 163.0', ' 44.43', '; 86.0', ' 74.95', '; 91.0', ' 160.0', '; 19.0', ' 82.83', ' 70.75', ' 35.69', ' 59.27', ' 123.0', '; 55.0', ' 81.37', ' 69.08', '; 80.0', ' 99.63', '; 63.0', ' 43.55', ' 54.07', '; 94.0', ' 182.0', ' 31.07', '; 29.4', ' 60.15', ' 69.19', ' 73.94', ' 129.5', '102.88', ' 51.96', ' 36.12', ' 82.27', '108.86', ' 63.53', ' 53.98', ' 82.87', '; 29.4', '; 72.0', ' 74.34', ' 65.17', '; 40.1', '103.93', ' 33.95', '; 60.0', '; 40.0', '; 55.0', '; 51.0', '101.73', '; 70.0', ' 84.77', '; 55.7', '129.59', '; 90.7', ' 85.01', '; 58.0', '; 22.9', '104.81', ' 26.79', '; 43.7', '; 77.0', ' 55.66', ' 98.99', '; 80.0', '; 50.0', ' 37.21', '; 73.0', ' 66.34', ' 80.05', ' 57.75', '; 66.2', '197.59', '; 68.8', '; 92.0', ' 98.04', '; 92.0', '3016.0', ' 74.74', ' 90.12', ' 143.0', ' 77.07', ' 105.0', ' 230.0', '; 72.0', ' 110.0', '; 63.2', ' 43.28', '; 68.1', '; 63.0', '; 62.0', '; 69.7', ' 100.0', ' 145.0', '103.15', ' 67.81', '148.66', ' 74.88', '; 61.2', ' 37.31', '; 45.5', ' 134.0', ' 37.25', ' 96.33', ' 127.0', ' 80.71', ' 77.79', ' 150.0', '110.57', ' 171.8', '115.41', ' 51.72', ' 60.55', '; 43.0', ' 76.79', '87.252', '; 44.8', ' 77.93', ' 16.15', ' 125.0', ' 24.25', '; 67.0', '; 88.0', '; 53.0', ' 66.15', ' 190.0', '103.48', ' 67.56', '123.79', '; 69.0', '; 71.2', ' 71.98', ' 56.98', ' 78.88', ' 66.61', ' 93.97', '; 68.6', ' 82.27', ' 29.68', '; 94.3', '; 31.8', '119.32', ' 160.0', ' 50.35', '124.36', '100.49', '; 20.5', '; 68.5', ' 75.51', '176.98', ' 95.02', ' 152.0', ' 71.26', ' 65.03', ' 71.63', '; 75.0', '; 23.0', ' 54.13', '; 60.0', ' 72.09', ' 66.16', '117.89', ' 56.68', ' 98.48', '; 85.0', ' 109.0', '; 57.7', ' 46.75', ' 95.22', '; 96.1', ' 75.49', '; 92.0', '; 55.0', ' 123.0', '; 57.0', ' 68.63', ' 77.88', '; 70.0', '; 52.5', '; 98.0', ' 65.38', ' 87.58', '105.36', ' 63.29', ' 67.53', ' 72.33', ' 38.05', ' 45.73', '; 92.0', ' 89.69', ' 78.29', '; 65.0', ' 34.93', ' 91.11', ' 42.18', ' 51.83', '; 64.0', '; 68.0', '115.91', ' 55.79', ' 69.79', '; 84.0', '; 56.0', ' 65.36', '; 67.0', ' 76.27', ' 67.99', '; 85.0', ' 390.0', ' 58.77', ' 27.75', ' 203.1', ' 33.01', ' 72.35', ' 83.82', ' 41.11', '; 67.6', ' 32.17', ' 78.85', ' 87.81', ' 58.75', '152.37', ' 113.1', '; 71.0', ' 60.16', '; 93.2', ' 58.62', ' 82.94', '; 58.0', '; 30.0', '; 75.0', '; 60.0', ' 89.75', '; 56.0', ' 72.33', '; 45.0', '; 65.0', ' 38.05', ' 92.37', ' 65.72', ' 53.59', '; 95.2', ' 36.93', '; 89.0', '; 55.0', '; 80.0', ' 80.95', ' 107.0', ' 76.06', '107.45', ' 59.73', '118.17', '; 34.2', ' 150.0', '; 62.0', ' 72.35', ' 81.43', ' 39.48', ' 76.17', '; 42.0', ' 47.98', ' 68.12', '; 80.0', ' 42.69', ' 34.42', '119.88', ' 84.75', '; 89.0', '116.42', ' 60.28', '; 47.0', '; 90.0', '173.94', '; 58.0', '; 63.0', ' 89.74', ' 209.0', ' 80.07', ' 72.33', ' 95.03', '119.44', '; 77.0', '115.02', '; 82.0', '; 64.4', ' 57.42', ' 95.47', ' 150.0', ' 88.55', '123.86', ' 85.54', '; 84.0', ' 70.74', '; 26.0', ' 99.83', '; 90.8', ' 70.64', ' 83.08', ' 62.88', '; 27.0', ' 64.81', ' 37.47', ' 96.43', ' 110.0', ' 67.99', ' 63.75', ' 132.0', ' 61.96', '; 45.0', ' 54.44', '; 81.3', ' 69.36', ' 88.55', '; 48.0', '; 40.0', ' 217.0', ' 67.66', ' 130.0', '; 88.0', ' 89.86', ' 32.94', ' 80.99', ' 24.95', '; 77.0', ' 95.08', ' 71.63', '; 28.0', ' 83.78', '; 62.0', '; 94.0', ' 121.0', '; 80.0', ' 71.48', '; 54.5', ' 111.4', '124.84', ' 76.81', '; 28.9', '146.63', ' 98.04', '; 92.5', '112.27', ' 67.78', ' 54.15', ' 56.45', '; 82.0', ' 96.83', '; 86.5', '; 46.0', ' 135.0', '; 37.0', '212.39', ' 76.42', ' 90.24', '143.22', ' 44.05', ' 80.59', ' 79.21', '; 53.0', ' 120.0', ' 54.74', '; 91.0', ' 121.0', '167.36', ' 70.68', '5 ; 3.', ' 99.65', ' 93.16', ' 195.0', ' 74.25', ' 33.99', '; 75.5', ' 200.0', ' 81.11', ' 72.64', ' 105.0', '; 89.0', ' 67.53', '; 30.0', ' 40.65', '; 60.0', '; 69.0', ' 48.31', ' 164.0', '; 29.0', ' 87.11', ' 96.44', ' 73.33', ' 120.0', ' 84.62', ' 25.95', ' 23.75', ' 30.79', ' 77.09', ' 52.62', ' 93.61', ' 52.08', '; 87.0', ' 66.69', '100.66', ' 72.47', ' 65.48', '; 23.0', '101.69', '143.54', ' 81.36', ' 56.45', ' 101.5', ' 74.36', ' 66.35', ' 172.0', '111.49', '; 76.3', '126.82', ' 33.21', ' 83.18', ' 56.61', '110.41', ' 95.34', '; 65.6', ' 53.23', ' 100.0', ' 90.94', '130.78', ' 98.77', ' 85.22', '; 67.0', '131.92', ' 96.67', ' 96.55', '121.15', '; 53.0', '; 65.3', ' 82.15', ' 76.15', ' 85.69', ' 93.48', ' 98.02', '; 61.0', ' 65.31', '; 72.0', '166.34', '; 30.0', '110.73', '; 65.0', ' 77.66', '; 30.0', '; 41.0', ' 68.33', ' 62.77', ' 156.1', '; 40.0', '; 11.0', ' 56.65', '; 23.5', ' 56.85', ' 63.46', ' 56.25', ' 92.94', '; 49.0', '106.22', '; 44.0', ' 113.0', ' 57.71', ' 24.95', '104.01', ' 29.19', '; 89.0', '120.06', ' 72.81', '; 35.0', ' 74.15', '; 47.0', ' 66.32', ' 67.58', ' 99.29', ' 107.0', '; 74.0', ' 36.27', ' 68.12', ' 73.87', ' 68.71', '; 84.0', '; 45.0', ' 27.55', '; 84.4', '; 56.0', '82.045', ' 241.0', ' 49.98', ' 158.0', '; 81.5', '; 57.0', '; 58.0', ' 80.72', '; 91.0', ' 127.5', ' 58.51', '; 20.5', '104.52', ' 88.63', ' 37.11', '; 30.0', ' 88.61', ' 81.58', '136.15', '; 81.0', '1376.0', '; 70.0', ' 126.7', ' 62.23', '; 83.7', ' 69.62', ' 172.0', '; 20.5', ' 60.72', ' 99.78', ' 27.45', ' 84.78', ' 90.66', ' 42.29', '; 66.0', ' 225.0', '174.93', '; 98.0', ' 53.03', '100.53', ' 30.77', '; 82.0', ' 106.0', ' 41.56', '102.97', '; 93.4', ' 64.19', '; 59.0', '; 73.0']

The list above comprises of the corresponding size of the prices we refined earlier, the sizes seems to have an identical pattern like the prices before cleaning, we can see there are whitespaces, some with semicolon and lastly they size class is a string which we will have to eradicate too. Firstly, we need to remove all whitspaces and semicolons.

In [16]:
final_size = []
for sizes in rough_size:
    final_size.append(sizes.replace(";", "").replace(" ", ""))
print(final_size)

['56.85', '95.13', '75.0', '108.58', '64.0', '69.94', '52.5', '185.5', '57.62', '126.78', '96.1', '53.0', '147.36', '33.21', '212.1', '59.37', '134.02', '123.0', '99.2', '99.39', '42.4', '70.28', '144.17', '65.96', '35.1', '42.5', '88.3', '58.07', '101.55', '54.8', '42.0', '116.0', '132.0', '95.95', '66.9', '90.0', '105.0', '29.13', '113.1', '74.0', '119.85', '53.26', '88.0', '105.0', '53.7', '53.74', '87.81', '56.25', '23.86', '62.0', '22.35', '54.6', '59.35', '29.87', '41.0', '46.02', '98.0', '58.55', '91.0', '67.0', '115.0', '140.0', '83.0', '39.13', '57.7', '72.55', '103.33', '66.29', '80.0', '65.76', '178.4', '72.4', '74.5', '98.43', '97.445', '59.39', '73.26', '81.0', '93.0', '60.23', '50.0', '57.35', '29.76', '117.23', '104.0', '83.37', '74.38', '43.0', '31.97', '53.23', '400.0', '91.57', '86.79', '89.44', '129.54', '64.41', '37.1', '20.5', '182.0', '62.38', '54.9', '76.0', '48.0', '36.29', '102.36', '130.0', '58.0', '171.76', '20.5', '01.', '90.67', '85.27', '33.54', '102.23', '95.23', '102.56', '186.0', '93.93', '60.38', '56.0', '94.17', '72.27', '99.44', '89.15', '77.79', '157.45', '122.65', '31.9', '73.97', '75.0', '88.0', '64.86', '98.67', '78.0', '79.2', '129.0', '115.39', '30.59', '126.7', '122.83', '64.5', '43.71', '98.43', '91.84', '47.63', '54.12', '49.74', '143.54', '96.6', '86.42', '86.55', '91.86', '59.03', '29.95', '85.0', '90.0', '108.0', '15.0', '66.85', '70.68', '68.78', '171.06', '74.07', '69.1', '96.5', '49.0', '131.0', '141.32', '60.75', '46.5', '68.54', '26.79', '36.0', '68.88', '60.0', '50.0', '101.5', '93.2', '104.0', '73.31', '58.05', '101.0', '82.5', '41.42', '60.98', '53.34', '71.04', '85.12', '94.52', '63.09', '78.95', '59.0', '67.88', '65.0', '95.98', '136.9', '86.0', '64.33', '158.0', '35.69', '42.29', '87.5', '43.68', '39.0', '99.62', '94.21', '95.1', '130.0', '86.03', '110.72', '103.14', '122.67', '44.87', '63.17', '62.96', '43.1', '71.41', '19.34', '87.3', '90.29', '88.61', '78.24', '79.33', '163.0', '44.43', '86.0', '74.95', '91.0', '160.0', '19.0', '82.83', '70.75', '35.69', '59.27', '123.0', '55.0', '81.37', '69.08', '80.0', '99.63', '63.0', '43.55', '54.07', '94.0', '182.0', '31.07', '29.4', '60.15', '69.19', '73.94', '129.5', '102.88', '51.96', '36.12', '82.27', '108.86', '63.53', '53.98', '82.87', '29.4', '72.0', '74.34', '65.17', '40.1', '103.93', '33.95', '60.0', '40.0', '55.0', '51.0', '101.73', '70.0', '84.77', '55.7', '129.59', '90.7', '85.01', '58.0', '22.9', '104.81', '26.79', '43.7', '77.0', '55.66', '98.99', '80.0', '50.0', '37.21', '73.0', '66.34', '80.05', '57.75', '66.2', '197.59', '68.8', '92.0', '98.04', '92.0', '3016.0', '74.74', '90.12', '143.0', '77.07', '105.0', '230.0', '72.0', '110.0', '63.2', '43.28', '68.1', '63.0', '62.0', '69.7', '100.0', '145.0', '103.15', '67.81', '148.66', '74.88', '61.2', '37.31', '45.5', '134.0', '37.25', '96.33', '127.0', '80.71', '77.79', '150.0', '110.57', '171.8', '115.41', '51.72', '60.55', '43.0', '76.79', '87.252', '44.8', '77.93', '16.15', '125.0', '24.25', '67.0', '88.0', '53.0', '66.15', '190.0', '103.48', '67.56', '123.79', '69.0', '71.2', '71.98', '56.98', '78.88', '66.61', '93.97', '68.6', '82.27', '29.68', '94.3', '31.8', '119.32', '160.0', '50.35', '124.36', '100.49', '20.5', '68.5', '75.51', '176.98', '95.02', '152.0', '71.26', '65.03', '71.63', '75.0', '23.0', '54.13', '60.0', '72.09', '66.16', '117.89', '56.68', '98.48', '85.0', '109.0', '57.7', '46.75', '95.22', '96.1', '75.49', '92.0', '55.0', '123.0', '57.0', '68.63', '77.88', '70.0', '52.5', '98.0', '65.38', '87.58', '105.36', '63.29', '67.53', '72.33', '38.05', '45.73', '92.0', '89.69', '78.29', '65.0', '34.93', '91.11', '42.18', '51.83', '64.0', '68.0', '115.91', '55.79', '69.79', '84.0', '56.0', '65.36', '67.0', '76.27', '67.99', '85.0', '390.0', '58.77', '27.75', '203.1', '33.01', '72.35', '83.82', '41.11', '67.6', '32.17', '78.85', '87.81', '58.75', '152.37', '113.1', '71.0', '60.16', '93.2', '58.62', '82.94', '58.0', '30.0', '75.0', '60.0', '89.75', '56.0', '72.33', '45.0', '65.0', '38.05', '92.37', '65.72', '53.59', '95.2', '36.93', '89.0', '55.0', '80.0', '80.95', '107.0', '76.06', '107.45', '59.73', '118.17', '34.2', '150.0', '62.0', '72.35', '81.43', '39.48', '76.17', '42.0', '47.98', '68.12', '80.0', '42.69', '34.42', '119.88', '84.75', '89.0', '116.42', '60.28', '47.0', '90.0', '173.94', '58.0', '63.0', '89.74', '209.0', '80.07', '72.33', '95.03', '119.44', '77.0', '115.02', '82.0', '64.4', '57.42', '95.47', '150.0', '88.55', '123.86', '85.54', '84.0', '70.74', '26.0', '99.83', '90.8', '70.64', '83.08', '62.88', '27.0', '64.81', '37.47', '96.43', '110.0', '67.99', '63.75', '132.0', '61.96', '45.0', '54.44', '81.3', '69.36', '88.55', '48.0', '40.0', '217.0', '67.66', '130.0', '88.0', '89.86', '32.94', '80.99', '24.95', '77.0', '95.08', '71.63', '28.0', '83.78', '62.0', '94.0', '121.0', '80.0', '71.48', '54.5', '111.4', '124.84', '76.81', '28.9', '146.63', '98.04', '92.5', '112.27', '67.78', '54.15', '56.45', '82.0', '96.83', '86.5', '46.0', '135.0', '37.0', '212.39', '76.42', '90.24', '143.22', '44.05', '80.59', '79.21', '53.0', '120.0', '54.74', '91.0', '121.0', '167.36', '70.68', '53.', '99.65', '93.16', '195.0', '74.25', '33.99', '75.5', '200.0', '81.11', '72.64', '105.0', '89.0', '67.53', '30.0', '40.65', '60.0', '69.0', '48.31', '164.0', '29.0', '87.11', '96.44', '73.33', '120.0', '84.62', '25.95', '23.75', '30.79', '77.09', '52.62', '93.61', '52.08', '87.0', '66.69', '100.66', '72.47', '65.48', '23.0', '101.69', '143.54', '81.36', '56.45', '101.5', '74.36', '66.35', '172.0', '111.49', '76.3', '126.82', '33.21', '83.18', '56.61', '110.41', '95.34', '65.6', '53.23', '100.0', '90.94', '130.78', '98.77', '85.22', '67.0', '131.92', '96.67', '96.55', '121.15', '53.0', '65.3', '82.15', '76.15', '85.69', '93.48', '98.02', '61.0', '65.31', '72.0', '166.34', '30.0', '110.73', '65.0', '77.66', '30.0', '41.0', '68.33', '62.77', '156.1', '40.0', '11.0', '56.65', '23.5', '56.85', '63.46', '56.25', '92.94', '49.0', '106.22', '44.0', '113.0', '57.71', '24.95', '104.01', '29.19', '89.0', '120.06', '72.81', '35.0', '74.15', '47.0', '66.32', '67.58', '99.29', '107.0', '74.0', '36.27', '68.12', '73.87', '68.71', '84.0', '45.0', '27.55', '84.4', '56.0', '82.045', '241.0', '49.98', '158.0', '81.5', '57.0', '58.0', '80.72', '91.0', '127.5', '58.51', '20.5', '104.52', '88.63', '37.11', '30.0', '88.61', '81.58', '136.15', '81.0', '1376.0', '70.0', '126.7', '62.23', '83.7', '69.62', '172.0', '20.5', '60.72', '99.78', '27.45', '84.78', '90.66', '42.29', '66.0', '225.0', '174.93', '98.0', '53.03', '100.53', '30.77', '82.0', '106.0', '41.56', '102.97', '93.4', '64.19', '59.0', '73.0']

Semicolons, whitespaces are all taken out from the list above, lastly we need to convert all to float.

In [18]:
final_size1 = []
for stringss in final_size:
    final_size1.append(float(stringss))
print(final_size1)

[56.85, 95.13, 75.0, 108.58, 64.0, 69.94, 52.5, 185.5, 57.62, 126.78, 96.1, 53.0, 147.36, 33.21, 212.1, 59.37, 134.02, 123.0, 99.2, 99.39, 42.4, 70.28, 144.17, 65.96, 35.1, 42.5, 88.3, 58.07, 101.55, 54.8, 42.0, 116.0, 132.0, 95.95, 66.9, 90.0, 105.0, 29.13, 113.1, 74.0, 119.85, 53.26, 88.0, 105.0, 53.7, 53.74, 87.81, 56.25, 23.86, 62.0, 22.35, 54.6, 59.35, 29.87, 41.0, 46.02, 98.0, 58.55, 91.0, 67.0, 115.0, 140.0, 83.0, 39.13, 57.7, 72.55, 103.33, 66.29, 80.0, 65.76, 178.4, 72.4, 74.5, 98.43, 97.445, 59.39, 73.26, 81.0, 93.0, 60.23, 50.0, 57.35, 29.76, 117.23, 104.0, 83.37, 74.38, 43.0, 31.97, 53.23, 400.0, 91.57, 86.79, 89.44, 129.54, 64.41, 37.1, 20.5, 182.0, 62.38, 54.9, 76.0, 48.0, 36.29, 102.36, 130.0, 58.0, 171.76, 20.5, 1.0, 90.67, 85.27, 33.54, 102.23, 95.23, 102.56, 186.0, 93.93, 60.38, 56.0, 94.17, 72.27, 99.44, 89.15, 77.79, 157.45, 122.65, 31.9, 73.97, 75.0, 88.0, 64.86, 98.67, 78.0, 79.2, 129.0, 115.39, 30.59, 126.7, 122.83, 64.5, 43.71, 98.43, 91.84, 47.63, 54.12, 49.74, 143.54, 96.6, 86.42, 86.55, 91.86, 59.03, 29.95, 85.0, 90.0, 108.0, 15.0, 66.85, 70.68, 68.78, 171.06, 74.07, 69.1, 96.5, 49.0, 131.0, 141.32, 60.75, 46.5, 68.54, 26.79, 36.0, 68.88, 60.0, 50.0, 101.5, 93.2, 104.0, 73.31, 58.05, 101.0, 82.5, 41.42, 60.98, 53.34, 71.04, 85.12, 94.52, 63.09, 78.95, 59.0, 67.88, 65.0, 95.98, 136.9, 86.0, 64.33, 158.0, 35.69, 42.29, 87.5, 43.68, 39.0, 99.62, 94.21, 95.1, 130.0, 86.03, 110.72, 103.14, 122.67, 44.87, 63.17, 62.96, 43.1, 71.41, 19.34, 87.3, 90.29, 88.61, 78.24, 79.33, 163.0, 44.43, 86.0, 74.95, 91.0, 160.0, 19.0, 82.83, 70.75, 35.69, 59.27, 123.0, 55.0, 81.37, 69.08, 80.0, 99.63, 63.0, 43.55, 54.07, 94.0, 182.0, 31.07, 29.4, 60.15, 69.19, 73.94, 129.5, 102.88, 51.96, 36.12, 82.27, 108.86, 63.53, 53.98, 82.87, 29.4, 72.0, 74.34, 65.17, 40.1, 103.93, 33.95, 60.0, 40.0, 55.0, 51.0, 101.73, 70.0, 84.77, 55.7, 129.59, 90.7, 85.01, 58.0, 22.9, 104.81, 26.79, 43.7, 77.0, 55.66, 98.99, 80.0, 50.0, 37.21, 73.0, 66.34, 80.05, 57.75, 66.2, 197.59, 68.8, 92.0, 98.04, 92.0, 3016.0, 74.74, 90.12, 143.0, 77.07, 105.0, 230.0, 72.0, 110.0, 63.2, 43.28, 68.1, 63.0, 62.0, 69.7, 100.0, 145.0, 103.15, 67.81, 148.66, 74.88, 61.2, 37.31, 45.5, 134.0, 37.25, 96.33, 127.0, 80.71, 77.79, 150.0, 110.57, 171.8, 115.41, 51.72, 60.55, 43.0, 76.79, 87.252, 44.8, 77.93, 16.15, 125.0, 24.25, 67.0, 88.0, 53.0, 66.15, 190.0, 103.48, 67.56, 123.79, 69.0, 71.2, 71.98, 56.98, 78.88, 66.61, 93.97, 68.6, 82.27, 29.68, 94.3, 31.8, 119.32, 160.0, 50.35, 124.36, 100.49, 20.5, 68.5, 75.51, 176.98, 95.02, 152.0, 71.26, 65.03, 71.63, 75.0, 23.0, 54.13, 60.0, 72.09, 66.16, 117.89, 56.68, 98.48, 85.0, 109.0, 57.7, 46.75, 95.22, 96.1, 75.49, 92.0, 55.0, 123.0, 57.0, 68.63, 77.88, 70.0, 52.5, 98.0, 65.38, 87.58, 105.36, 63.29, 67.53, 72.33, 38.05, 45.73, 92.0, 89.69, 78.29, 65.0, 34.93, 91.11, 42.18, 51.83, 64.0, 68.0, 115.91, 55.79, 69.79, 84.0, 56.0, 65.36, 67.0, 76.27, 67.99, 85.0, 390.0, 58.77, 27.75, 203.1, 33.01, 72.35, 83.82, 41.11, 67.6, 32.17, 78.85, 87.81, 58.75, 152.37, 113.1, 71.0, 60.16, 93.2, 58.62, 82.94, 58.0, 30.0, 75.0, 60.0, 89.75, 56.0, 72.33, 45.0, 65.0, 38.05, 92.37, 65.72, 53.59, 95.2, 36.93, 89.0, 55.0, 80.0, 80.95, 107.0, 76.06, 107.45, 59.73, 118.17, 34.2, 150.0, 62.0, 72.35, 81.43, 39.48, 76.17, 42.0, 47.98, 68.12, 80.0, 42.69, 34.42, 119.88, 84.75, 89.0, 116.42, 60.28, 47.0, 90.0, 173.94, 58.0, 63.0, 89.74, 209.0, 80.07, 72.33, 95.03, 119.44, 77.0, 115.02, 82.0, 64.4, 57.42, 95.47, 150.0, 88.55, 123.86, 85.54, 84.0, 70.74, 26.0, 99.83, 90.8, 70.64, 83.08, 62.88, 27.0, 64.81, 37.47, 96.43, 110.0, 67.99, 63.75, 132.0, 61.96, 45.0, 54.44, 81.3, 69.36, 88.55, 48.0, 40.0, 217.0, 67.66, 130.0, 88.0, 89.86, 32.94, 80.99, 24.95, 77.0, 95.08, 71.63, 28.0, 83.78, 62.0, 94.0, 121.0, 80.0, 71.48, 54.5, 111.4, 124.84, 76.81, 28.9, 146.63, 98.04, 92.5, 112.27, 67.78, 54.15, 56.45, 82.0, 96.83, 86.5, 46.0, 135.0, 37.0, 212.39, 76.42, 90.24, 143.22, 44.05, 80.59, 79.21, 53.0, 120.0, 54.74, 91.0, 121.0, 167.36, 70.68, 53.0, 99.65, 93.16, 195.0, 74.25, 33.99, 75.5, 200.0, 81.11, 72.64, 105.0, 89.0, 67.53, 30.0, 40.65, 60.0, 69.0, 48.31, 164.0, 29.0, 87.11, 96.44, 73.33, 120.0, 84.62, 25.95, 23.75, 30.79, 77.09, 52.62, 93.61, 52.08, 87.0, 66.69, 100.66, 72.47, 65.48, 23.0, 101.69, 143.54, 81.36, 56.45, 101.5, 74.36, 66.35, 172.0, 111.49, 76.3, 126.82, 33.21, 83.18, 56.61, 110.41, 95.34, 65.6, 53.23, 100.0, 90.94, 130.78, 98.77, 85.22, 67.0, 131.92, 96.67, 96.55, 121.15, 53.0, 65.3, 82.15, 76.15, 85.69, 93.48, 98.02, 61.0, 65.31, 72.0, 166.34, 30.0, 110.73, 65.0, 77.66, 30.0, 41.0, 68.33, 62.77, 156.1, 40.0, 11.0, 56.65, 23.5, 56.85, 63.46, 56.25, 92.94, 49.0, 106.22, 44.0, 113.0, 57.71, 24.95, 104.01, 29.19, 89.0, 120.06, 72.81, 35.0, 74.15, 47.0, 66.32, 67.58, 99.29, 107.0, 74.0, 36.27, 68.12, 73.87, 68.71, 84.0, 45.0, 27.55, 84.4, 56.0, 82.045, 241.0, 49.98, 158.0, 81.5, 57.0, 58.0, 80.72, 91.0, 127.5, 58.51, 20.5, 104.52, 88.63, 37.11, 30.0, 88.61, 81.58, 136.15, 81.0, 1376.0, 70.0, 126.7, 62.23, 83.7, 69.62, 172.0, 20.5, 60.72, 99.78, 27.45, 84.78, 90.66, 42.29, 66.0, 225.0, 174.93, 98.0, 53.03, 100.53, 30.77, 82.0, 106.0, 41.56, 102.97, 93.4, 64.19, 59.0, 73.0]

Now we have a cleaned list of sizes and we can go ahead and convert to a DataFrame so we can prepare price and size DataFrame for concatenation.

In [19]:
size_df = pd.DataFrame(final_size1)

In [20]:
size_df.head()

        0
0   56.85
1   95.13
2   75.00
3  108.58
4   64.00

In [21]:
# concatenating both price_df and size_df as one DataFrme
real_estate_df = pd.concat([price_df, size_df], axis=1)

In [22]:
real_estate_df.head()

         0       0
0   470.00   56.85
1   720.00   95.13
2  1870.00   75.00
3  1699.28  108.58
4   879.00   64.00

Looking at the Data Frame above, everything seems right except for the name of the column which doesn't reflect the records below it. The column names have to be rename to what the record looks like. Since we are dealing with price and size, then we can go ahead and assign both column to this names.

In [23]:
real_estate_df.columns = ['Price', 'Size(mÂ²)']

In [25]:
real_estate_df.head(5)

     Price  Size(mÂ²)
0   470.00     56.85
1   720.00     95.13
2  1870.00     75.00
3  1699.28    108.58
4   879.00     64.00

Columns name successfully changed

In [26]:
#estimating the price per meter for each apartment and creating a column to accomodate the result simultaneously
real_estate_df["Price_per_mÂ²"] = round(real_estate_df["Price"] / real_estate_df["Size(mÂ²)"], 2)

In [27]:
real_estate_df.head()

     Price  Size(mÂ²)  Price_per_mÂ²
0   470.00     56.85          8.27
1   720.00     95.13          7.57
2  1870.00     75.00         24.93
3  1699.28    108.58         15.65
4   879.00     64.00         13.73

In [22]:
# saving as csv file 
real_estate_df.to_csv('final_cleaned.csv')